// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU4FA5f8n4pSjcRG2RDEJpXeNwmdRufHk',
    appId: '1:1092674861696:web:699ab8e9681fa437380465',
    messagingSenderId: '1092674861696',
    projectId: 'amuts-project',
    authDomain: 'amuts-project.firebaseapp.com',
    storageBucket: 'amuts-project.appspot.com',
    measurementId: 'G-FCTDTV4Y1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3t18msLwTJDhYAnZtoi91UnkbQhYocug',
    appId: '1:1092674861696:android:79ada35efff48e11380465',
    messagingSenderId: '1092674861696',
    projectId: 'amuts-project',
    storageBucket: 'amuts-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGM8R0AVqrOAyheLZViSh2KBDE_Mlzcyk',
    appId: '1:1092674861696:ios:76cee6b2fe92ca83380465',
    messagingSenderId: '1092674861696',
    projectId: 'amuts-project',
    storageBucket: 'amuts-project.appspot.com',
    iosBundleId: 'com.example.amutsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGM8R0AVqrOAyheLZViSh2KBDE_Mlzcyk',
    appId: '1:1092674861696:ios:76cee6b2fe92ca83380465',
    messagingSenderId: '1092674861696',
    projectId: 'amuts-project',
    storageBucket: 'amuts-project.appspot.com',
    iosBundleId: 'com.example.amutsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU4FA5f8n4pSjcRG2RDEJpXeNwmdRufHk',
    appId: '1:1092674861696:web:e5c53aeb5f14147d380465',
    messagingSenderId: '1092674861696',
    projectId: 'amuts-project',
    authDomain: 'amuts-project.firebaseapp.com',
    storageBucket: 'amuts-project.appspot.com',
    measurementId: 'G-MHRWE2STQG',
  );
}
